export interface InterviewV2Content {
  birthDate: string;
  weight: string;
  height: string;
  sex: string;
  mainSymptoms: string;
  symptomDuration: string;
  symptomFrequency: string;
  symptomTriggers: string;
  historicalSymptoms: string;
  medicationsSupplementsHerbs: string;
  dailyFluids: string;
  bowelMovements: string;
  workType: string;
  infectionTendency: string;
  mealsLocation: string;
  mealsPerDay: string;
  snacking: string;
  breakfast: string;
  secondBreakfast: string;
  secondBreakfastTime: string;
  lunch: string;
  lunchTime: string;
  dinner: string;
  dinnerTime: string;
  intolerancesAllergies: string;
  flavorEnhancers: string;
  addictions: string;
  petsAtHome: string;
  cycleRegularity: string;
  darkBreadFrequency: string;
  whiteBreadFrequency: string;
  groatsFrequency: string;
  honeyFrequency: string;
  jamsFrequency: string;
  sweetsFrequency: string;
  eggsFrequency: string;
  whiteMeatFrequency: string;
  fishSeafoodFrequency: string;
  butterFrequency: string;
  margarineFrequency: string;
  creamFrequency: string;
  fruitsFrequency: string;
  vegetablesFrequency: string;
  legumesFrequency: string;
  milkFrequency: string;
  kefirYogurtFrequency: string;
  yellowCheeseFrequency: string;
  notes: string;
}

export const EMPTY_INTERVIEW_V2: InterviewV2Content = {
  birthDate: "",
  weight: "",
  height: "",
  sex: "",
  mainSymptoms: "",
  symptomDuration: "",
  symptomFrequency: "",
  symptomTriggers: "",
  historicalSymptoms: "",
  medicationsSupplementsHerbs: "",
  dailyFluids: "",
  bowelMovements: "",
  workType: "",
  infectionTendency: "",
  mealsLocation: "",
  mealsPerDay: "",
  snacking: "",
  breakfast: "",
  secondBreakfast: "",
  secondBreakfastTime: "",
  lunch: "",
  lunchTime: "",
  dinner: "",
  dinnerTime: "",
  intolerancesAllergies: "",
  flavorEnhancers: "",
  addictions: "",
  petsAtHome: "",
  cycleRegularity: "",
  darkBreadFrequency: "",
  whiteBreadFrequency: "",
  groatsFrequency: "",
  honeyFrequency: "",
  jamsFrequency: "",
  sweetsFrequency: "",
  eggsFrequency: "",
  whiteMeatFrequency: "",
  fishSeafoodFrequency: "",
  butterFrequency: "",
  margarineFrequency: "",
  creamFrequency: "",
  fruitsFrequency: "",
  vegetablesFrequency: "",
  legumesFrequency: "",
  milkFrequency: "",
  kefirYogurtFrequency: "",
  yellowCheeseFrequency: "",
  notes: "",
};
